#!/bin/bash
set -e

branch=$1
. cri-lock-repos
. cri-common
select_xenbranch
. ap-common

case "$branch" in
xen*)
	./sg-hg-heads sh -ec '
		cd "'"$repos/$branch.hg"'"
	        hg pull -u >&2
	        eval "$1"
	' x
	;;
qemu-upstream-*)
        repo_tree_rev_fetch_git $branch \
		$TREE_QEMU_UPSTREAM master $LOCALREV_QEMU_UPSTREAM
        ;;
linux)
	repo_tree_rev_fetch_git linux \
		$TREE_LINUX $TAG_LINUX $LOCALREV_LINUX
	;;
linux-2.6.39)
	repo_tree_rev_fetch_git linux \
		$TREE_LINUX2639 $TAG_LINUX2639 $LOCALREV_LINUX
	;;
linux-xen-*)
	repo_tree_rev_fetch_git linux \
		$TREE_LINUX xen/next-${branch#linux-xen-} $LOCALREV_LINUX
	;;
*)
	echo >&2 "branch $branch ?"
	exit 1
	;;
esac
