#!/bin/bash
set -e

branch=$1
xenbranch=$1

. cri-lock-repos
. ap-common

case "$branch" in
xen*)
	./sg-hg-heads sh -ec '
		cd "'"$repos/$branch.hg"'"
	        hg pull -u >&2
	        eval "$1"
	' x
	;;
linux)
	cd $repos/xen
	git fetch -f $TREE_LINUX $TAG_LINUX:$LOCALREV_LINUX
	git-rev-parse $LOCALREV_LINUX
	;;
*)
	echo >&2 "branch $branch ?"
	exit 1
	;;
esac
