#!/bin/bash
set -e

branch=$1
xenbranch=$1

. cri-lock-repos
. ap-common

case "$branch" in
xen*)
        echo $TREE_XEN
	;;
qemu-upstream-*)
        echo $TREE_QEMU_UPSTREAM
        ;;
linux)
	echo $TREE_LINUX
	;;
linux-2.6.39)
	echo $TREE_LINUX2639
	;;
*)
	echo >&2 "branch $branch ?"
	exit 1
	;;
esac
