#!/bin/bash
set -e

: ${CACHEING_GIT_CACHE:=/volatile/git-cache}

echo "using cache $CACHEING_GIT_CACHE..."

if ! test -d "${CACHEING_GIT_CACHE}"; then
	mkdir "${CACHEING_GIT_CACHE}"
	echo >&2 'cache directory ($CACHEING_GIT_CACHE) does not exist'
	exit 127
fi

if [ "x$CACHEING_GIT_CACHE_LOCKED" != "x$CACHEING_GIT_CACHE" ]; then
	export CACHEING_GIT_CACHE_LOCKED="$CACHEING_GIT_CACHE"
	exec with-lock-ex -w "$CACHEING_GIT_CACHE/lock" "$0" "$@"
fi

echo "locked cache $CACHEING_GIT_CACHE..."

if ! test -x "$0"; then
        echo >&2 "myself is $0 but not executable ?"
        exit 127
fi

for git in `type -pa git`; do
        if [ -x "$git" ] && ! cmp $git "$0" >/dev/null; then
                REAL_GIT=$git
                break
        fi
done

if [ "x$REAL_GIT" = x ]; then
        echo >&2 "$0: did not find git that wasn't me"
        exit 127
fi

if ! test -d "$CACHEING_GIT_CACHE"/.git; then
	echo "initialising cache $CACHEING_GIT_CACHE..."
	(cd "$CACHEING_GIT_CACHE" && git-init-db --shared)
fi

case "$1" in
clone)
	echo "processing $0 $@..."
        subcmd="$1"; shift
        $REAL_GIT "$subcmd" --reference $CACHEING_GIT_CACHE "$@"
	;;
*)
	echo "running git $@..."
	exec $REAL_GIT "$@" ;;
esac

case "$subcmd" in
clone)
	while [ $# -gt 1 ]; do shift; done
	if ! test -d "$1"; then
		echo \
 "not updating cache; last arg \`$1' seems not to be dest dir"
		exit 0
	fi
	relevant="$1"
        cacheid=`basename "$1"`
	;;
*)
	echo >&2 "$0: internal error $1"
	exit 1
	;;
esac

echo "updating cache $CACHEING_GIT_CACHE $cacheid..."

mkdir_p () {
        if test -d "$1"; then return; fi
        mkdir "$1"
}

cache="$CACHEING_GIT_CACHE"/.git

mkdir_p "$cache"/refs
mkdir_p "$cache"/refs/caches
mkdir_p "$cache"/refs/caches/"$cacheid"

${RSYNC-rsync} -r "$relevant"/.git/objects/. "$cache"/objects/.
${RSYNC-rsync} --exclude=HEAD \
               -r "$relevant"/.git/refs/.    "$cache"/refs/caches/"$cacheid"/.
