#!/bin/bash
set -ex

. cri-args-hostlists
branch=$1; shift
select_branch

check_stop daily.

fetch_version () {
	if [ "x$1" = "x$branch" ]; then
		./ap-fetch-version "$@"
	else
		./ap-fetch-version-baseline "$@"
	fi
}

if [ "x$REVISION_XEN" = x ]; then
        REVISION_XEN="`fetch_version $xenbranch`"
        export REVISION_XEN
fi
if [ "x$REVISION_LINUX" = x ]; then
        REVISION_LINUX="`fetch_version linux`"
        export REVISION_LINUX
fi
if [ "x$OLD_REVISION" = x ]; then
        OLD_REVISION="`./ap-fetch-version-old $branch`"
        export OLD_REVISION
fi

wantpush=$OSSTEST_PUSH

case "$tree" in
xen)
	NEW_REVISION=$REVISION_XEN
	;;
linux)
	NEW_REVISION=$REVISION_LINUX
	export REVISION_LINUX_XCP=disable
	export REVISION_LINUX_OLD=disable
	;;
*)
	NEW_REVISION=''
	wantpush=false
	;;
esac

if [ "x$NEW_REVISION" = "x$OLD_REVISION" ]; then
        wantpush=false
        if [ $branch != xen-unstable ]; then
		echo 'up to date'
                exit 0
        fi
fi

if test -e $mrof; then mv $mrof $mrof.old; fi
touch $mrof; rm $mrof
rm -f tmp/bisected.$branch.*

flight=`./make-flight $branch $xenbranch $OSSTEST_BLESSING "$@"`

case "$NEW_REVISION/$OLD_REVISION" in
*/*[^0-9a-f]* | *[^0-9a-f]*/*)
        echo >&2 "NO SGR COMPARISON badchar $NEW_REVISION/$OLD_REVISION"
        ;;
[0-9a-f]*/[0-9a-f]*)
        sgr_args+=" --machine-readable-output=$mrof"
        sgr_args+=" --this-$tree=$NEW_REVISION"
	if $wantpush; then
	        sgr_args+=" --that-$tree=$OLD_REVISION"
	fi
        ;;
*)
        echo >&2 "NO SGR COMPARISON wronglen $NEW_REVISION/$OLD_REVISION"
        ;;
esac

execute_flight $flight $OSSTEST_BLESSING

exec >tmp/$flight.email
cat $OSSTEST_EMAIL_HEADER
printf 'Subject: [%s test] ' "$branch"

flight_html_dir=$OSSTEST_HTMLPUB_DIR/
job_html_dir=$OSSTEST_HTML_DIR/

globallockdir=`perl -e 'use Osstest; readconfigonly(); print $c{GlobalLockDir} or die $!'`

with-lock-ex -w $globallockdir/report-lock \
  ./sg-report-job-history --html-dir=$job_html_dir --flight=$flight

./sg-report-flight --html-dir=$flight_html_dir/$flight/ $sgr_args $flight

push=false
if grep '^tolerable$' $mrof >/dev/null 2>&1; then push=$wantpush; fi
if test -f $branch.force; then push=$OSSTEST_PUSH; fi
if test -f $branch.block; then push=false; fi

if ! $wantpush; then
        echo
        echo "Published tested tree is already up to date."
        echo
elif $push; then
        echo
        echo "Pushing revision $to_push:"
        echo
        to_push=`sed -n "s/^version this $tree //p" <$mrof`
	case "$to_push" in
	*[^0-9a-f]*)
		echo >&2 "BAD PUSH REVISION $to_push"
		;;
	[0-9a-f]*)
	        if ./ap-push $branch $to_push 2>&1; then
			rm -f $branch.push
			perl -i~ -pe '
	                        next unless m/^Subject: / && !$subsequent++;
	                        s/$/ - PUSHED/;
	                ' tmp/$flight.email
	        fi
		;;
	*)	echo >&2 "BAD/MISSING PUSH REVISION $to_push" ;;
	esac
else
        echo
        echo Not pushing.
        echo
fi

exec >&2

./cr-publish-flight-logs $flight

send_email tmp/$flight.email
