#!/bin/bash
set -ex

. cri-args-hostlists

branch=$1; shift

sgr_args="$flight"

if [ "x$REVISION_XEN" = x ]; then
        REVISION_XEN="`./ap-fetch-version $branch`"
        export REVISION_XEN
fi
if [ "x$OLD_REVISION_XEN" = x ]; then
        OLD_REVISION_XEN="`./ap-fetch-version-old $branch`"
        export OLD_REVISION_XEN
fi

if [ "x$REVISION_XEN" = "x$OLD_REVISION_XEN" ] && \
   [ $branch != xen-unstable ]; then
        exit 0
fi

if test -e $mrof; then mv $mrof $mrof.old; fi
touch $mrof; rm $mrof
rm -f bisected.$branch.*

case "$REVISION_XEN/$OLD_REVISION_XEN" in
*/*[^0-9a-f]* | *[^0-9a-f]*/*) ;;
        echo >&2 "NO SGR COMPARISON badchar $REVISION_XEN/$OLD_REVISION_XEN"
        ;;
????????????/????????????)
        sgr_args+=" --this-xen=$REVISION_XEN --that-xen=$OLD_REVISION_XEN"
        sgr_args+=" --machine-readable-output=$mrof"
        ;;
*)
        echo >&2 "NO SGR COMPARISON wronglen $REVISION_XEN/$OLD_REVISION_XEN"
        ;;
esac

flight=`./make-flight $branch "$@"`

execute_flight $flight $OSSTEST_BLESSING

exec >tmp/$flight.email
cat $OSSTEST_EMAIL_HEADER
printf 'Subject: '

./sg-report-flight $sgr_args

push=false
if grep '^tolerable$' $mrof >/dev/null 2>&1; then push=true; fi
if test -f $branch.force; then push=true; fi
if test -f $branch.inhibit; then push=false; fi

if $push; then
        echo
        echo "Pushing:"
        echo
        to_push=`sed -n 's/^version this xen //p' <$mrof`
        if ./ap-push $branch $to_push 2>&1; then
                rm -f $branch.push
        fi
fi

exec >&2

send_email tmp/$flight.email
