#!/bin/bash
# usage: cr-for-branches WLEM "SCRIPT OPTIONS" ARGS...
# will run   with-lock-ex WLEM SCRIPT OPTIONS BRANCH ARGS...

set -e

wlem=$1; shift

LOGFILE=tmp/cr-for-branches.log
export LOGFILE

BRANCHES='xen-4.0-testing xen-unstable linux'
export BRANCHES

export LOCK_ACQUIRE_START=`date +%s`

with-lock-ex $wlem global-lock bash -ec '
        savelog -n 500 $LOGFILE >/dev/null
        exec >>$LOGFILE

        log () {
                d=`date +"%Y-%m-%d %H:%M:%S %Z"`
                printf "[%s $$] %s%s\n" "$d" "$m" "$1"
        }

	lock_acquire_done=`date +%s`
	lock_acquire_delay=$(( $lock_acquire_done - $LOCK_ACQUIRE_START ))
	lock_acquire_max=28800
	if [ $lock_acquire_delay -gt $lock_acquire_max ]; then
		log "$script $lock_acquire_delay > $lock_acquire_max, shedding"
		exit 1
	fi

        script=$1; shift
        for branch in $BRANCHES; do
                if ! git-pull . incoming:master; then
                        git-checkout HEAD
                fi

                m="$script $branch $*"
                log ...
                set +e
                $script $branch "$@" 2>&1
                rc=$?
                set -e
                log " status=$rc"
                if [ $rc != 0 ]; then
                        cat >&2 <<END
FAILURE $$
$m
see $LOGFILE

END
                        cat >&2 $LOGFILE
                        exit $rc
                fi
        done
' x "$@"
