#!/bin/bash
# usage: cr-for-branches WLEM "SCRIPT OPTIONS" ARGS...
# will run   with-lock-ex WLEM SCRIPT OPTIONS BRANCH ARGS...

set -e

wlem=$1; shift
scriptoptions="$1"; shift

LOGFILE=tmp/cr-for-branches.log
export LOGFILE

BRANCHES='xen-4.0-testing xen-unstable linux'
export BRANCHES

with-lock-ex -w data-tree-lock bash -ec '
	git-pull . incoming:master ||:
	git-checkout HEAD
'

export OSSTEST_TEST_PULLFROM=`pwd`

for branch in $BRANCHES; do
 (
	set -e
	cd ../branches/for-$branch.git

	export LOCK_ACQU_START=`date +%s`

	with-lock-ex $wlem data-tree-lock bash -ec '
		m="$*"

		mkdir -p tmp

		savelog -n 500 $LOGFILE >/dev/null
		exec >>$LOGFILE

		log () {
			d=`date +"%Y-%m-%d %H:%M:%S %Z"`
			printf "[%s $$] %s %s\n" "$d" "$m" "$1"
		}

		lock_acquire_done=`date +%s`
		lock_acquire_delay=$(( $lock_acquire_done - $LOCK_ACQU_START ))
		lock_acquire_max=86400
		if [ $lock_acquire_delay -gt $lock_acquire_max ]; then
			log "$lock_acquire_delay > $lock_acquire_max, shedding"
			exit 1
		fi

		log ...

		git-pull $OSSTEST_TEST_PULLFROM master:master ||:
		git-pull . incoming:master ||:
		git-checkout HEAD

		set +e
		"$@" 2>&1
		rc=$?
		set -e
		log "status=$rc"
		if [ $rc != 0 ]; then
                        cat >&2 <<END
FAILURE $$
$m
see $LOGFILE

END
			cat >&2 $LOGFILE
			exit $rc
                fi
	' x $scriptoptions $branch "$@"
 ) &

${OSSTEST_FOR_BRANCHES_WAIT-sleep 100}

done
