#!/usr/bin/perl -w

use strict qw(refs vars);
use Fcntl qw(:flock);
use Osstest;

our %c;

readconfigonly();

die "usage: ./cr-publish-flight-logs <flight>" unless @ARGV==1;

my $flight= shift @ARGV;
die unless $flight =~ m/^\d+$/;

open LOCK, "> publish-lock" or die $!;
flock LOCK, LOCK_EX or die $!;

my $githost= $c{HarnessPublishGitUserHost};
my $gitdir= $c{HarnessPublishGitRepoDir};

system_checked("git-push $githost:$gitdir HEAD:flight-$flight");
system_checked("ssh $githost 'cd $gitdir && git-update-server-info'");

sub copydir ($$) {
    my ($src,$dst) = @_;
    my @cmd= qw(rsync --compress --compress-level=9 --stats --delete -auH);
    #--bwlimit=50
    push @cmd, $src, $dst;
    print "+ @cmd\n";
    $!=0; $?=0; system @cmd; die "rsync $? $!" if $? or $!;
}

copydir("$c{Logs}/$flight/", "$c{LogsPublish}/$flight");
copydir("$c{Results}/", "$c{ResultsPublish}");
