#!/usr/bin/perl -w

use strict qw(refs vars);

use Osstest;

our %c;

require 'config.pl';

die "usage: ./cr-publish-flight-logs <flight>" unless @ARGV==1;

my $flight= shift @ARGV;
die unless $flight =~ m/^\d+$/;

system_checked("git-push $c{HarnessPublishGitUserHost}:$c{HarnessPublishGitRepoDir} HEAD:flight-$flight");
system_checked("ssh $c{HarnessPublishGitUserHost} 'cd $c{HarnessPublishGitRepoDir} && git-update-server-info'");

our @cmd= qw(rsync --compress --compress-level=9 --stats --delete -auH);
#--bwlimit=50
push @cmd, "$c{Logs}/$flight/", "$c{LogsPublish}/$flight";
print "+ @cmd\n";
$!=0; $?=0; system @cmd; die "rsync $? $!" if $? or $!;
