#!/bin/bash
set -ex

. cri-args-hostlists
branch=$1

if test -f $branch.stop; then exit 0; fi
if test -f bisect.stop; then exit 0; fi

sticky=bisecting-sticky-branch

if ! test -f $branch.mro; then
        rm -f $sticky
        echo "$branch no mro"
        exit 0
fi

if test -f $sticky; then
        read <$sticky sticky_branch
        if [ "x$sticky_branch" != "x$branch" ]; then
                echo "$branch but sticky $sticky_branch, skipping"
                exit 0
        fi
fi

compute_state () {
        reportfile=tmp/$flight.bisection-report
        summaryfile=tmp/$flight.bisection-summary
        bisleaf=bisect.$job.${testid//\//--}

        echo "computing $job $testid $*"

        set +e
        ./cs-bisection-step --graph-out=$OSSTEST_HTML_DIR/$bisleaf \
                --summary-out=$summaryfile \
                --blessings=$OSSTEST_BLESSING,$OSSTEST_BLESSING-bisect \
                "$@" $branch $job $testid >$reportfile 2>&1
        rc=$?
        set -e

        case $rc in
        0)      echo work to do; return ;;
        4)      how=completed ;;
        8)      how=inconclusive ;;
        12)     how=inconsistent ;;
        16)     how=unreproducible ;;

        *)      echo >&2 "FAILED $job $testid $rc $* "
                cat >&2 $reportfile
                exit 1
                ;;
        esac

        echo ended $how
        touch $flagfile
        send_bisection_email "bisection $how"
        rm -f $sticky
        exit 0
}

perhaps_bisect_step () {
        flagfile=tmp/bisected.$job.$testid
        if test -f $flagfile; then
                echo "already completed $job $testid"
                return
        fi

        flight=`./cs-flight-create $branch`
        flight_executed=false

        compute_state --flight=$flight
        send_bisection_email "oss xen test: bisection underway"

        echo $branch >$sticky.new
        mv -f $sticky.new $sticky

        execute_flight $flight $OSSTEST_BLESSING-bisect
        flight_executed=true

        compute_state
        send_bisection_email "bisection intermediate results"
	exit 0
}


send_bisection_email () {
        echo emailing "$1"

        exec 3>tmp/$flight.email
        cat >&3 $OSSTEST_EMAIL_HEADER
        cat >&3 <<END
Subject: oss xen test: $1

branch $branch
job $job
test $testid

END
        cat >&3 $summaryfile
        cat >&3 <<END

For bisection revision-tuple graph see:
   $OSSTEST_HTML_URL/$bisleaf.ps
Revision IDs in each graph node refer, respectively, to the Trees above.

----------------------------------------
END
        cat >&3 $reportfile
        if $flight_executed; then
                echo >&3 ----------------------------------------
                ./sg-report-flight >&3 $flight
        fi
        exec 3>&-
        send_email tmp/$flight.email
}        

exec <$branch.mro
while read keyword job testid; do
        if [ "x$keyword" = xregression ]; then
                perhaps_bisect_step
        fi
done

echo nothing to do
exit 0
