#!/usr/bin/perl -w
#
# args:
#   <flight> <blessing>

use strict qw(vars);
use DBI;
use Osstest;

csreadconfig();

die unless @ARGV >= 3;
my ($flight,$blessing,@oldblessings) = @ARGV;

my $q= $dbh_tests->
    prepare("UPDATE FLIGHTS SET blessing=? WHERE flight=?");

db_retry($dbh_tests, sub {
    dbfl_check($flight, [@oldblessings]);
    $q->execute($blessing, $flight);
});
