#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

csreadconfig();

@ARGV==1 or die $!;
our ($branch) = @ARGV;

my ($flight) =
    db_retry($dbh_tests,[qw(flights)], sub {
        $dbh_tests->do("INSERT INTO flights VALUES".
                       " (DEFAULT,DEFAULT,'constructing',?)", {}, $branch);
        my $fl= $dbh_tests->
            selectrow_array('SELECT MAX(flight) FROM flights');
        dbfl_check($fl,'constructing');
        return $fl
    });

printf "%s\n", $flight;
