#!/usr/bin/perl -w
#
# args:
#   <flight> <blessing>

use strict qw(vars);
use DBI;
use Osstest;

csreadconfig();

die unless @ARGV >= 3;
my ($flight,$blessing,@oldblessings) = @ARGV;

db_retry($dbh_tests, sub {
    my $q= $dbh_tests->
        prepare("UPDATE FLIGHTS SET blessing=? WHERE flight=?");
    dbfl_exec($flight,[@oldblessings], $blessing, $flight);
});
