#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

csreadconfig();

@ARGV==1 or die $!;
our ($branch) = @ARGV;

my ($flight) = 
    db_retry($dbh_tests, sub {
        $dbh_tests->do("INSERT INTO flights VALUES".
                       " (DEFAULT,DEFAULT,'constructing',?)", {}, $branch);
        dbfl_check($flight,'constructing');
        return $dbh_tests->
            selectrow_array('SELECT MAX(flight) FROM flights');
    });

printf "%s\n", $flight;
