#!/bin/bash
set -ex

branch=xen-unstable
dcs=daily-cron-settings

if [ "x$1" = "x--real" ]; then
	: ${OSSTEST_BLESSING:=real}
	shift
elif [ "x$1" = "x--like-real" ]; then
	: ${OSSTEST_CRON_SETTINGS:=$dcs-real}
	shift
fi	
: ${OSSTEST_BLESSING:=play}

if [ x"$OSSTEST_BLESSING" = xreal ]; then
	cd ${OSSTEST_DIR:=/export/home/osstest/testing.git}
fi

: ${OSSTEST_EMAIL_HEADER:=daily-cron-email-$OSSTEST_BLESSING}

. ${OSSTEST_CRON_SETTINGS:-$dcs-$OSSTEST_BLESSING}

: ${ARCH_RUNVARS_i386:="host=$OSSTEST_HOST_i386"}
: ${ARCH_RUNVARS_amd64:="host=$OSSTEST_HOST_amd64"}
export ARCH_RUNVARS_i386
export ARCH_RUNVARS_amd64

if [ "x$OSSTEST_HOST_i386" != x"$OSSTEST_HOST_amd64" ]; then
	hostlists1="$OSSTEST_HOST_i386 $OSSTEST_HOST_amd64"
else
	hostlists1="$OSSTEST_HOST_i386"
fi

export PAIR_RUNVARS="src_host=$OSSTEST_PAIR_HOST1 dst_host=$OSSTEST_PAIR_HOST2"
hostlists2=`perl -e 'print join ",", sort @ARGV' \
	$OSSTEST_PAIR_HOST1 $OSSTEST_PAIR_HOST2`

sgr_args="$flight"

if [ "x$REVISION_XEN" = x ]; then
        REVISION_XEN="`./ap-fetch-version $branch`"
        export REVISION_XEN
fi
if [ "x$OLD_REVISION_XEN" = x ]; then
        OLD_REVISION_XEN="`./ap-fetch-version-old $branch`"
        export OLD_REVISION_XEN
fi

if [ "x$REVISION_XEN" = "x$OLD_REVISION_XEN" ]; then
        exit 0
fi

mrof="$branch.mro"
if test -e $mrof; then mv $mrof $mrof.old; fi
touch $mrof; rm $mrof

case "$REVISION_XEN/$OLD_REVISION_XEN" in
*/*[^0-9a-f]* | *[^0-9a-f]*/*) ;;
        echo >&2 "NO SGR COMPARISON badchar $REVISION_XEN/$OLD_REVISION_XEN"
        ;;
????????????/????????????)
        sgr_args+=" --this-xen=$REVISION_XEN --that-xen=$OLD_REVISION_XEN"
        sgr_args+=" --machine-readable-output=$mrof"
        ;;
*)
        echo >&2 "NO SGR COMPARISON wronglen $REVISION_XEN/$OLD_REVISION_XEN"
        ;;
esac

flight=`./make-flight $branch "$@"`

./execute-flight $flight $OSSTEST_BLESSING \
        "$hostlists1" "$hostlists2" \
        >tmp/$flight.transcript 2>&1

cat tmp/$flight.transcript >&2

exec >tmp/$flight.email
cat $OSSTEST_EMAIL_HEADER
printf 'Subject: '

./sg-report-flight $sgr_args

push=false
if grep '^tolerable$' $mrof >/dev/null 2>&1; then push=true; fi
if test -f $branch.force; then push=true; fi
if test -f $branch.inhibit; then push=false; fi

if $push; then
        echo
        echo "Pushing:"
        echo
        to_push=`sed -n 's/^version this xen //p' <$mrof`
        if ./ap-push $branch $to_push 2>&1; then
                rm -f $branch.push
        fi
fi

exec >&2

/usr/sbin/sendmail -odi -oee -oi -t <tmp/$flight.email
rm tmp/$flight.email

