#!/bin/bash
set -ex
if [ $# -lt 3 ]; then cat <<END >&2; exit 1

usage: ./execute-flight FLIGHT BLESSING HOSTLISTS+
 eg ./execute-flight 1330 play 'earwig bedbug'

END
fi

flight="$1"; shift
blessing="${1-play}"; shift

trap "
	set +e
	./cs-flight-bless $flight crashed running
	exit 1
" 0

set -x
./cs-flight-bless $flight running constructing
for hostlist in $1; do
	(
		date
		./sg-run-builds $flight --hostlist=$hostlist
		date
		./sg-run-builds $flight --hostlist=$hostlist
		date
		./sg-run-builds $flight --hostlist=$hostlist
		date
	) &
	: spawned builds $! $hostlist
done
wait

while [ $# -ge 1 ]; do
   : hostlists "$1"
   for hostlist in $1; do
	(
	date
	./sg-run-tests $flight --hostlist=$hostlist
	date
	./sg-run-tests $flight --hostlist=$hostlist
	date
	./sg-run-tests $flight --hostlist=$hostlist
	date
	./sg-run-tests $flight --hostlist=$hostlist
	date
	) &
	: spawned tests $! $hostlist
  done
  wait
  shift
done

./cs-flight-bless $flight "$blessing" running
trap "" 0
