#!/bin/sh
set -e

branch=$1
xenbranch=$2
buildflight=$3

flight=`./cs-flight-create $branch`

: ${TREE_LINUX:=git://git.kernel.org/pub/scm/linux/kernel/git/jeremy/xen.git}

if [ x$buildflight = x ]; then

  for arch in i386 amd64; do

    eval "
	arch_runvars=\"\$ARCH_RUNVARS_$arch\"
    "

    ./cs-job-create $flight build-$arch build				     \
		arch=$arch						     \
	tree_qemu=git://mariner.uk.xensource.com/qemu-$xenbranch.git	     \
	tree_xen=http://hg.uk.xensource.com/$xenbranch.hg		     \
		$RUNVARS $BUILD_RUNVARS $arch_runvars			     \
		host_hostflags=build,arch-$arch				     \
		xen_kernels=linux-2.6-pvops				     \
		revision_xen=$REVISION_XEN				     \
		revision_qemu=$REVISION_QEMU				     \
		tree_linux=$TREE_LINUX					     \
		revision_linux=$REVISION_LINUX

    if [ "x$REVISION_LINUX_OLD" != xdisable ]; then

      ./cs-job-create $flight build-$arch-oldkern build			\
		arch=$arch						\
	tree_qemu=git://mariner.uk.xensource.com/qemu-$xenbranch.git	\
	tree_xen=http://hg.uk.xensource.com/$xenbranch.hg		\
		$RUNVARS $BUILD_RUNVARS $arch_runvars			\
		host_hostflags=build,arch-$arch				\
		xen_kernels=linux-2.6-xen				\
		revision_xen=$REVISION_XEN				\
		revision_qemu=$REVISION_QEMU				\
	tree_linux=http://hg.uk.xensource.com/linux-2.6.18-xen.hg	\
        revision_linux=$REVISION_LINUX_OLD

    fi

    if [ $arch = i386 -a "x$REVISION_LINUX_XCP" != xdisable ]; then
      # XCP dom0 kernel is 32-bit only

      ./cs-job-create $flight build-$arch-xcpkern build-kern		      \
		$RUNVARS $BUILD_RUNVARS $arch_runvars			      \
		arch=$arch						      \
		host_hostflags=build,arch-$arch				      \
	tree_linux=http://hg.uk.xensource.com/carbon/trunk/linux-2.6.27.hg    \
     tree_pq_linux=http://hg.uk.xensource.com/carbon/trunk/linux-2.6.27.pq.hg \
        revision_linux=$REVISION_LINUX_XCP				      \
        revision_pq_linux=$REVISION_PQ_LINUX_XCP

    fi

  done

else

  bfi=$buildflight.

fi

for xenarch in i386 amd64; do

  for kern in '' -xcpkern; do
	#  -oldkern   does not work on spider

    case $kern in
    '')
		kernkind=pvops
		;;
    -oldkern)
		kernkind=2618
		if [ "x$REVISION_LINUX_OLD" = xdisable ]; then continue; fi
		;;
    -xcpkern)
		kernkind=2627
		if [ "x$REVISION_LINUX_XCP" = xdisable ]; then continue; fi
		;;
    *)		echo >&2 "kernkind ?  $kern"; exit 1 ;;
    esac

    for dom0arch in i386 amd64; do

      eval "
	  arch_runvars=\"\$ARCH_RUNVARS_$dom0arch\"
      "

      if [ $dom0arch != $xenarch -a $xenarch != amd64 ]; then continue; fi

      if [ x$kern = x-xcpkern -a $dom0arch != i386 ]; then continue; fi

      most_hostflags="arch-$dom0arch,arch-$xenarch"

      most_runvars="
		arch=$dom0arch			        	\
		xenbuildjob=${bfi}build-$xenarch        	\
		kernbuildjob=${bfi}build-$dom0arch$kern 	\
		buildjob=${bfi}build-$dom0arch	        	\
		kernkind=$kernkind		        	\
		$arch_runvars
		"

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-pv test-debian \
		$RUNVARS $TEST_RUNVARS $most_runvars			  \
		debian_kernkind=$kernkind				  \
		debian_arch=$dom0arch   				  \
		all_hostflags=$most_hostflags

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-xl test-debian \
		$RUNVARS $TEST_RUNVARS $most_runvars			  \
		toolstack=xl						  \
		debian_kernkind=$kernkind				  \
		debian_arch=$dom0arch   				  \
		all_hostflags=$most_hostflags

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-win test-win	\
		$RUNVARS $TEST_RUNVARS $most_runvars			\
		win_image=winxpsp2.iso   				\
		all_hostflags=$most_hostflags

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-pair test-pair \
                !host $PAIR_RUNVARS $RUNVARS $TEST_RUNVARS $most_runvars  \
		debian_kernkind=$kernkind				  \
		debian_arch=$dom0arch   				  \
		all_hostflags=$most_hostflags

    done

  done

done

echo $flight
