#!/bin/sh
set -e

branch=$1
xenbranch=$2
blessing=$3
buildflight=$4

flight=`./cs-flight-create $blessing $branch`

. ap-common

if [ x$buildflight = x ]; then

  for arch in ${BUILD_ARCHES- i386 amd64 }; do

    if [ "x$arch" = xdisable ]; then continue; fi

    eval "
	arch_runvars=\"\$ARCH_RUNVARS_$arch\"
    "

    ./cs-job-create $flight build-$arch build				     \
		arch=$arch						     \
	tree_qemu=$TREE_QEMU	     \
	tree_xen=$TREE_XEN		     \
		$RUNVARS $BUILD_RUNVARS $BUILD_XEN_RUNVARS $arch_runvars     \
		host_hostflags=share-build-$arch,arch-$arch,purpose-build    \
		revision_xen=$REVISION_XEN				     \
		revision_qemu=$REVISION_QEMU

    ./cs-job-create $flight build-$arch-pvops build-kern		     \
		arch=$arch kconfighow=xen-enable-xen-config		     \
	tree_xen=$TREE_XEN		     \
		$RUNVARS $BUILD_RUNVARS $BUILD_LINUX_RUNVARS $arch_runvars   \
		host_hostflags=share-build-$arch,arch-$arch,purpose-build    \
		xen_kernels=linux-2.6-pvops				     \
		revision_xen=$REVISION_XEN				     \
		tree_linux=$TREE_LINUX					     \
		revision_linux=$REVISION_LINUX

    if [ "x$REVISION_LINUX_OLD" != xdisable ]; then

      ./cs-job-create $flight build-$arch-oldkern build			\
		arch=$arch						\
	tree_qemu=$TREE_QEMU	\
	tree_xen=$TREE_XEN		\
		$RUNVARS $BUILD_RUNVARS $BUILD_LINUX_OLD_RUNVARS	\
		$arch_runvars						\
		host_hostflags=share-build-$arch,arch-$arch,purpose-build \
		xen_kernels=linux-2.6-xen				\
		revision_xen=$REVISION_XEN				\
		revision_qemu=$REVISION_QEMU				\
	tree_linux=http://hg.uk.xensource.com/linux-2.6.18-xen.hg	\
        revision_linux=$REVISION_LINUX_OLD

    fi

    if [ $arch = i386 -a "x$REVISION_LINUX_XCP" != xdisable ]; then
      # XCP dom0 kernel is 32-bit only

      ./cs-job-create $flight build-$arch-xcpkern build-kern		      \
		$RUNVARS $BUILD_RUNVARS $BUILD_LINUX_XCP_RUNVARS	      \
		$arch_runvars						      \
		arch=$arch						\
	kconfighow=intree-buildconfigs kimagefile=arch/x86/boot/vmlinuz \
		host_hostflags=share-build-$arch,arch-$arch,purpose-build     \
		tree_xen=$TREE_XEN	      \
		revision_xen=$REVISION_XEN				      \
	tree_linux=$TREEBASE_LINUX_XCP.hg    \
     tree_pq_linux=$TREEBASE_LINUX_XCP.pq.hg \
        revision_linux=$REVISION_LINUX_XCP				      \
        revision_pq_linux=$REVISION_PQ_LINUX_XCP

    fi

  done

else

  bfi=$buildflight.

fi

for xenarch in ${TEST_ARCHES- i386 amd64 } ; do

  if [ "x$xenarch" = xdisable ]; then continue; fi

  for kern in '' -xcpkern; do

    case $kern in
    '')
                kernbuild=pvops
		kernkind=pvops
		;;
    -xcpkern)
                kernbuild=xcpkern
		kernkind=2627
		if [ "x$REVISION_LINUX_XCP" = xdisable ]; then continue; fi
		;;
    *)		echo >&2 "kernkind ?  $kern"; exit 1 ;;
    esac

    for dom0arch in i386 amd64; do

      eval "
	  arch_runvars=\"\$ARCH_RUNVARS_$dom0arch\"
      "

      if [ $dom0arch != $xenarch -a $xenarch != amd64 ]; then continue; fi

      if [ x$kern = x-xcpkern -a $dom0arch != i386 ]; then continue; fi

      most_hostflags="arch-$dom0arch,arch-$xenarch,purpose-test"

      most_runvars="
		arch=$dom0arch			        	\
		xenbuildjob=${bfi}build-$xenarch        	\
		kernbuildjob=${bfi}build-$dom0arch-$kernbuild 	\
		buildjob=${bfi}build-$dom0arch	        	\
		kernkind=$kernkind		        	\
		$arch_runvars
		"

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-pv test-debian \
		$RUNVARS $TEST_RUNVARS $most_runvars $TEST_PV_RUNVARS	  \
		debian_kernkind=$kernkind				  \
		debian_arch=$dom0arch   				  \
		all_hostflags=$most_hostflags

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-xl test-debian \
		$RUNVARS $TEST_RUNVARS $most_runvars $TEST_XL_RUNVARS	  \
		toolstack=xl						  \
		debian_kernkind=$kernkind				  \
		debian_arch=$dom0arch   				  \
		all_hostflags=$most_hostflags

        for vcpus in '' 1; do
            case "$vcpus" in
            '') vcpus_runvars=''; vcpus_suffix='' ;;
            *) vcpus_runvars=guests_vcpus=$vcpus; vcpus_suffix=-vcpus$vcpus ;;
            esac

            if [ "x$vcpus" = x ] || \
               [ "$xenarch$kern-$dom0arch" = "amd64-i386" ]; then

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-win$vcpus_suffix \
                test-win \
		$RUNVARS $TEST_RUNVARS $most_runvars $TEST_WIN_RUNVARS	\
		win_image=winxpsp2.iso $vcpus_runvars			\
		all_hostflags=$most_hostflags,hvm

            fi
        done
                

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-pair test-pair \
                !host $RUNVARS $TEST_RUNVARS $most_runvars $TEST_PAIR_RUNVARS \
		debian_kernkind=$kernkind				  \
		debian_arch=$dom0arch   				  \
		all_hostflags=$most_hostflags,equiv-1

      if [ $xenarch = amd64 -a $dom0arch = i386 ]; then

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-xl-multivcpu \
                        test-debian guests_vcpus=4 \
		$RUNVARS $TEST_RUNVARS $most_runvars $TEST_XL_RUNVARS	  \
		toolstack=xl						  \
		debian_kernkind=$kernkind				  \
		debian_arch=$dom0arch   				  \
		all_hostflags=$most_hostflags

      ./cs-job-create $flight test-$xenarch$kern-$dom0arch-xl-credit2   \
           test-debian guests_vcpus=4 xen_boot_append='sched=credit2'      \
		$RUNVARS $TEST_RUNVARS $most_runvars $TEST_XL_RUNVARS	  \
		toolstack=xl						  \
		debian_kernkind=$kernkind				  \
		debian_arch=$dom0arch   				  \
		all_hostflags=$most_hostflags

	for cpuvendor in amd intel; do

    ./cs-job-create $flight test-$xenarch$kern-$dom0arch-rhel6hvm-$cpuvendor \
						test-rhelhvm \
		$RUNVARS $TEST_RUNVARS $most_runvars $TEST_RHELHVM_RUNVARS \
		redhat_image=rhel-server-6.0-i386-dvd.iso		\
		toolstack=xl						\
		all_hostflags=$most_hostflags,hvm-$cpuvendor

	done

      fi

    done

  done

done

echo $flight
