#!/bin/bash
set -ex

job=$1
testid=$2
hostlists="$3"

# eg
#  ./step-bisect test-amd64-xcpkern-i386-win windows-install 'bedbug earwig'

bisfile=tmp/bisect.$job.$testid

while true; do
        flight=`./cs-create-flight`
        savelog $bisfile.dot
        savelog $bisfile.ps
        ./cs-bisection-step --graph-out=$bisfile --flight=$flight
        ./execute-flight $flight bisect "$hostlists"
done
