#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our $ho= selecthost($r{Host});

my $builddir= "/home/osstest/build-$r{Job}.$r{Task}";

sub build () {
    target_cmd($ho, "rm -rf $builddir && mkdir $builddir");
    target_cmd($ho, <<END, 300);
	set -xe
        cd $builddir
	hg clone '$r{Tree_Xen}' xen-unstable
	cd xen-unstable
	hg update '$r{Revision_Xen}'
	>.config
	echo >>.config GIT_HTTP=y
	echo >>.config QEMU_REMOTE='$r{Tree_Qemu}'
	echo >>.config QEMU_TAG='$r{Revision_Qemu}'
END
    target_cmd($ho, <<END, 3000);
	set -xe
        PATH=/usr/lib/ccache:\$PATH
	cd $builddir
        cd xen-unstable
        make -j4 2>&1 |tee ../log
        echo ok.
END
}   

need_rparams(qw(Tree_Xen Revision_Xen
                Tree_Qemu Revision_Qemu));

build();
