#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;
use File::Path;
use POSIX;

readconfig();
opendb_state();
our $ho= selecthost($r{host});

my $leaf= "build.$flight.$job";
my $builddir= "/home/osstest/$leaf";

sub build () {
    target_cmd($ho, "rm -rf $builddir && mkdir $builddir", 60);
    target_cmd($ho, <<END.
	set -xe
        cd $builddir
	hg clone '$r{tree_xen}' xen-unstable
	cd xen-unstable
	hg update '$r{revision_xen}'
	>.config
	echo >>.config GIT_HTTP=y
	echo >>.config QEMU_REMOTE='$r{tree_qemu}'
END
               (length($r{revision_qemu}) ? <<END : '').
	echo >>.config QEMU_TAG='$r{revision_qemu}'
END
               (length($r{xen_kernels}) ? <<END : '')
	echo >>.config KERNELS='$r{xen_kernels}'
END
               , 300);
    target_cmd($ho, <<END, 3000);
	set -xe
        PATH=/usr/lib/ccache:\$PATH
	cd $builddir
        cd xen-unstable
        (make -j4 2>&1 && touch ../build-ok-stamp) |tee ../log
        test -f ../build-ok-stamp
        echo ok.
END
}  

sub stash () {
}

need_runvars(qw(tree_xen revision_xen
                tree_qemu revision_qemu));

build();
built_stash($ho, $builddir, 'xen-unstable/dist/install', 'dist');
