#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our $ho= selecthost($r{host});

our $ram_mb=    512;
our $swap_mb=  1000;
our $disk_mb= 10000;

our $guesthost= 'one.guest.osstest';
our $gho;

our $ether= 'f4:fe:1b:60:78:c9';

sub prep () {
    target_install_packages_norec($ho, qw(lvm2 xen-tools));

    $gho= prepareguest($ho, 'debian', $guesthost, $ether,
                       $swap_mb + $disk_mb + 2);
    target_cmd_root($ho, "umount $gho->{Lvdev} ||:");
}

sub ginstall () {
    target_cmd_root($ho, <<END, 1000);
        xen-create-image \\
            --dhcp --memory ${ram_mb}M --swap ${swap_mb}M \\
            --dist $c{GuestSuite} \\
            --mirror http://$c{DebianMirrorHost}/$c{DebianMirrorSubpath} \\
            --hostname $gho->{Name} \\
            --lvm $gho->{Lv} --force \\
            --kernel $r{xen_kernel_path} \\
            --initrd /boot/initrd.img-$r{xen_kernel_ver} \\
END
    store_runvar("$gho->{Guest}_cfgpath", "/etc/xen/$gho->{Name}.cfg");
}

prep();
ginstall();
