#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our $ho= selecthost($r{host});
our $gho= selectguest(@ARGV ? $ARGV[0] : 'guest');

sub save () {
    guest_checkrunning($ho,$gho) or die $gho->{Name};
    my $err= guest_check_ip($gho);  die "$err $gho->{Name}" if defined $err;
    target_cmd_root($ho, "xm save $gho->{Name} image", 200);
    target_ping_check_down($gho);
}
sub restore () {
    target_cmd_root($ho, "xm restore image", 200);
    target_ping_check_up($gho);
}
sub checkok () {
    await_tcp(5,1, $gho);
    target_cmd_root($gho, "echo guest $gho->{Name}: restored")
        if $r{"$gho->{Guest}_tcpcheckport"} == 22;
}

guest_await_dhcp_tcp($gho, 5);
save();
restore();
checkok();
