#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our ($ho,$gho) = ts_get_host_guest(@ARGV);

sub save () {
    guest_checkrunning($ho,$gho) or die $gho->{Name};
    my $err= guest_check_ip($gho);  die "$err $gho->{Name}" if defined $err;
    target_cmd_root($ho,
		    toolstack()->{Command}
		    ." save $gho->{Name} image",
		    200);
    target_ping_check_down($gho);
}
sub restore () {
    target_cmd_root($ho,
		    toolstack()->{Command}
		    ." restore "
		    .(toolstack()->{RestoreNeedsConfig} ?
		      $r{ $gho->{Guest}.'_'. toolstack()->{CfgPathVar} } : '')
		    ." image", 200);
    target_ping_check_up($gho);
}

guest_await_dhcp_tcp($gho, 5);
save();
restore();
guest_check_up($gho);
