#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our ($ho,$gho) = ts_get_host_guest(@ARGV);

sub stop () {
    guest_checkrunning($ho, $gho) or die "$gho->{Name} not running";
    target_cmd_root($ho,
		    toolstack()->{Command}
		    ." shutdown -w "
		    .$gho->{Name}, 200);
    guest_checkrunning($ho, $gho) and die $gho->{Name};
}

guest_await_dhcp_tcp($gho, 5);
stop();
target_ping_check_down($gho);
