#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our ($ho,$gho) = ts_get_host_guest(@ARGV);

sub start () {
    guest_umount_lv($ho, $gho);
    my $cmd= toolstack()->{Command}." create ".
        $r{ $gho->{Guest}.'_'. toolstack()->{CfgPathVar} };
    target_cmd_root($ho, $cmd, 100);
}

sub checkstart () {
    guest_checkrunning($ho, $gho) or die $gho->{Name};
}

start();
checkstart();
guest_await($gho, 100);
guest_check_up($gho);
