#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our $ho= selecthost($r{host});
our $gho= selectguest(@ARGV ? $ARGV[0] : 'guest');

sub stop () {
    guest_checkrunning($ho, $gho) or die $gho->{Name};
    target_cmd_root($ho, "xm shutdown -w $gho->{Name}", 200);
    guest_checkrunning($ho, $gho) and die $gho->{Name};
}

guest_await_dhcp_tcp($gho, 5);
stop();
target_ping_check_down($gho);
