#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();

our ($whhost,$gn) = @ARGV;
$whhost ||= 'host';
$gn ||= 'redhat';

our $ho= selecthost($r{$whhost});

our $ram_mb=   1024;
our $disk_mb= 50000;

our $guesthost= "$gn.guest.osstest";
our $gho;

sub prep () {
    target_install_packages_norec($ho, qw(lvm2 rsync));

    $gho= prepareguest($ho, $gn, $guesthost, 22, $disk_mb + 1);

    more_prepareguest_hvm($ho,$gho, $ram_mb, $disk_mb);    
}

sub start () {
    target_cmd_root($ho, "xl create $gho->{CfgPath}", 100);
}

prep();
start();

guest_await_dhcp_tcp($gho,22);
guest_check_up($gho);
