#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our $ho= selecthost($r{host});
our $gho= selectguest('guest');

sub stop () {
    guest_xmrunning($ho, $gho) or die $gho->{Name};
    target_cmd_root($ho, "xm shutdown -w $gho->{Name}", 200);
    guest_xmrunning($ho, $gho) and die $gho->{Name};
}

guest_await($gho, 5,5);
stop();
target_ping_check_down($gho);
