#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our $ho= selecthost($r{host});
our $gho= selectguest('guest');

sub start () {
    guest_umount_lv($ho, $gho);
    target_cmd_root($ho, "xm create $r{$gho->{Guest}.'_cfgpath'}", 100);
}

sub checkstart () {
    guest_xmrunning($ho, $gho) or die $gho->{Name};
}

start();
checkstart();
guest_await($gho, 100,100);
