#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our $ho= selecthost($r{host});
our $gho;

our $ram_mb=    512;
our $disk_mb= 10000;

our $guesthost= 'win.guest.osstest';

sub prep () {
    target_install_packages_norec($ho, qw(lvm2 rsync));

    $gho= prepareguest($ho, 'win', $guesthost, 8936, $disk_mb + 1);

    store_runvar("$gho->{Guest}_pingbroken", 1);
}

sub start () {
    target_cmd_root($ho, "xm create $gho->{CfgPath}", 100);
}

prep();
hvm_prepareguest($ho,$gho, $ram_mb);
start();

guest_await_dhcp_tcp($gho,7000);
guest_check_up($gho);
