#!/usr/bin/perl -w

use Osstest;
readconfig();

die if @ARGV && $ARGV[0] =~ m/^-/;

logm("checking builds ...");

foreach my $k (sort keys %r) {
    next unless $k =~ m/^(?:.*_)?([^_]+)buildjob$/;
    my $part= $1;
    my $path= "path_${part}dist";
    logm("checking $k $path");
    get_stashed($path, $r{$k});
}

logm("all ok.");

exit 0;
