#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;
use File::Path;
use POSIX;
use OsstestDebian;

my $checkmode= 0;

readconfig();
opendb_state();

our @hos;

if (@ARGV and $ARGV[0] eq '--check') {
    $checkmode= 1;
    shift @ARGV;
    logm("checking builds are done...");
} else {
    if (!@ARGV) {
	push @ARGV, 'host';
    }
    foreach my $k (@ARGV) {
        push @hos, selecthost($k);
    }
}

our $ho;

my %distpath;

sub packages () {
    target_install_packages($ho,
                            qw(bridge-utils vncsnapshot
                               libsdl1.2debian));
    if ($r{arch} eq 'i386') {
	target_install_packages($ho, 'libc6-xen');
    }
}

sub extract_one ($$$) {
    my ($part, $path, $job) = @_;
    $distpath{$part}= get_stashed($path, $job);
    return if $checkmode;
    my $local= $path;  $local =~ s/path_//;
    my $distcopy= "/root/extract_$local.tar.gz";
    target_putfile_root($ho, 300, $distpath{$part}, $distcopy);
    target_cmd_root($ho, "cd / && tar zxf $distcopy", 300);
}

sub extract () {
    foreach my $part ('', 'kern', 'xen') {
        extract_one($part, "path_${part}dist", $r{"${part}buildjob"});
    }
}

sub adjustconfig () {
    target_editfile_root($ho, "/etc/xen/xend-config.sxp",
			 "xend-config.sxp", sub {
	my (@domains) = (qw(localhost localhost.localdomain),
			 ".".$c{Domain}, ".".$c{TestHostDomain});
	logm("relocation domains: @domains");
	foreach (@domains) {
	    s/\./\\$&/g;
	    s/^/^/g;
	    s/$/\$/g;
	    s/^\^(\\\.)/.\*$1/;
	}
	$_= join ' ', @domains;
	s/[\'\\]/\\$&/g;
	my $extra= "(xend-relocation-hosts-allow '$_')";
	logm("relocation setting: $extra");
	$extra .= "\n";
        while (<EI>) {
	    s/^\s*\(xend-relocation-hosts-allow/#$&/;
	    print EO or die $!;
	    if (m/^\#\(xend-relocation-hosts-allow/) {
		print EO $extra or die $!;
		$extra= '';
	    }
	}
	print EO $extra or die $!;
    });

    my $trace_config_file;
    foreach my $try (qw(/etc/default/xencommons
                        /etc/sysconfig/xencommons
                        /etc/default/xend
                        /etc/sysconfig/xend)) {
        next unless target_file_exists($ho, $try);
        $trace_config_file= $try;
        last;
    }
    die unless defined $trace_config_file;

    target_editfile_root($ho, $trace_config_file, sub {
        my $prnow;
        $prnow= sub {
            print EO "XENCONSOLED_TRACE=guest\n" or die $!;
            $prnow= sub { };
        };
        while (<EI>) {
            print EO or die $! unless m/^XENCONSOLED_TRACE/;
            $prnow->() if m/^#XENCONSOLED_TRACE/;
        }
        print EO "\n" or die $!;
        $prnow->();
    });

    target_cmd_root($ho, 'mkdir -p /var/log/xen/console');
}

sub setupboot () {
    my $xenhopt= "com1=$c{Baud},8n1 console=com1,vga gdb=com1 conswitch=x".
        " watchdog";
    if (toolstack()->{Dom0MemFixed}) {
        $xenhopt .= " dom0_mem=512M";
    }
    my $append= $r{xen_boot_append};
    $xenhopt .= " $append" if defined $append;

    debian_boot_setup($ho, $xenhopt, \%distpath);

    logm("ready to boot Xen");
}

our $initscripts_nobridge;

sub setupinitd () {
    my $ts= toolstack();
    my $xencommons= '/etc/init.d/xencommons';
    my $have_xencommons=
        !!target_cmd_output_root($ho, <<END);
 if test -f $xencommons && ! grep 'FOR USE WITH LIBXL' $xencommons >/dev/null
 then
   echo y
 fi
END
    $initscripts_nobridge= !defined($ts->{OldDaemonInitd}) || $have_xencommons;
    logm("init.d scripts ".
         ($initscripts_nobridge
          ? 'do not mess with bridge, doing it in interfaces(5)'
          : '_do_ mess with bridge, letting them handle it'));
    my $cmd= '';
    my $updatercd= sub {
        my ($script,$start) = @_;
        $cmd .= "\n    update-rc.d $script start $start 2 .";
    };
    if ($initscripts_nobridge) {
        my $script= $have_xencommons ? 'xencommons' : 'xenlightdaemons';
        $updatercd->($script,92);
        my $pri= 93;
        foreach my $d (@{ $ts->{NewDaemons} }) {
            $updatercd->("$d",$pri);
            $pri++;
        }
    } else {
        my $initd= $ts->{OldDaemonInitd};
        $updatercd->($initd,93) if defined $initd;
        $updatercd->('xenbridge',38) if $ts->{OldSeparateBridgeInitd};
    }
    target_cmd_root($ho, $cmd);
}

sub nodhcp () {
    my ($iface,$bridgex);
    if ($initscripts_nobridge) {
        $iface= 'xenbr0';
        $bridgex= <<END;
    bridge_ports eth0
    bridge_fd 0
    bridge_stp off
END
    } else {
        $iface= 'eth0';
        $bridgex= '';
    }
logm("iface $iface >$initscripts_nobridge<");
    target_editfile_root($ho, "/etc/network/interfaces",
                         "etc-network-interfaces", sub {
        my $suppress= 0;
        while (<EI>) {
            $suppress= 0 unless m/^\s+/;
            s/^ \s* allow-hotplug \s+ (?: eth0 | xenbr0 ) \s* $
                /auto $iface\n/x;
            if (m/^\s* iface \s+ (?: eth0 | xenbr0 ) \s+ inet \s /x) {
                $suppress= 1;
                print EO <<END;
iface $iface inet static
    address $ho->{Ip}
    netmask $c{NetNetmask}
    gateway $c{NetGateway}
$bridgex
END
            }
            print EO or die $!
                unless $suppress;
        }
    });
}    

if ($checkmode) {
    extract();
} else {
    die if @hos > 1;
    $ho= $hos[0];
    
    packages();
    extract();
    adjustconfig();
    setupboot();
    setupinitd();
    nodhcp();
}
