#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;

readconfig();
opendb_state();
our $ho= selecthost($r{host});

sub prep () {
    target_install_packages($ho,
                            qw(mercurial build-essential bin86 bcc iasl
                               libpci-dev libncurses5-dev libssl-dev python-dev
                               libx11-dev git-core uuid-dev gettext gawk
                               libsdl-dev
			       ccache));
}

prep();
