#!/usr/bin/perl -w

use strict qw(vars);
use DBI;
use Osstest;
use File::Path;
use POSIX;

readconfig();
opendb_state();
our $ho= selecthost($r{host});

my $leaf= "build.$flight.$job";
my $builddir= "/home/osstest/$leaf";

sub build () {
    my $kerns= $r{xen_kernels};
    $kerns =~ s/,/ /g;
    
    target_cmd($ho, "rm -rf $builddir && mkdir $builddir", 60);
    target_cmd($ho, <<END.
	set -xe
        cd $builddir
	hg clone '$r{tree_xen}' xen-unstable
	cd xen-unstable
	hg update '$r{revision_xen}'
	>.config
	echo >>.config GIT_HTTP=y
	echo >>.config QEMU_REMOTE='$r{tree_qemu}'
END
               (length($r{revision_qemu}) ? <<END : '').
	echo >>.config QEMU_TAG='$r{revision_qemu}'
END
               (length($kerns) ? <<END : '')
	echo >>.config KERNELS='$kerns'
END
               , 300);
    target_cmd($ho, <<END, 3000);
	set -xe
        PATH=/usr/lib/ccache:\$PATH
	cd $builddir
        cd xen-unstable
        (make -j4 2>&1 && touch ../build-ok-stamp) |tee ../log
        test -f ../build-ok-stamp
        echo ok.
END
}  

sub divide () {
    target_cmd($ho, <<END, 100);
        set -xe
        cd $builddir/xen-unstable/dist
        mkdir kerninstall xeninstall
        if test -d install/boot; then
            mv install/boot kerninstall/.
            if test -f kerninstall/boot/xen.gz; then
                mkdir xeninstall/boot
                mv kerninstall/boot/xen* xeninstall/boot/.
            fi
        fi
END
}

sub stash () {
    foreach my $part ('', 'kern', 'xen') {
        built_stash($ho, $builddir,
                    "xen-unstable/dist/${part}install",
                    "${part}dist");
    }
}

need_runvars(qw(tree_xen revision_xen
                tree_qemu revision_qemu));

build();
divide();
stash();
